services:
  db:
    image: postgres:14.1-alpine
    privileged: true
    restart: always
    env_file:
      - .env
    ports:
      - '54320:5432'
  api:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    restart: on-failure:2
    environment:
      DB_HOST: db
    ports:
      - '8000:8000'
    develop:
      watch:
        - action: sync+restart
          path: ./app
          target: /code/app
        - action: rebuild
          path: Pipfile