version: '3.3'
services:
  db:
    image: postgres:14.1-alpine
    privileged: true
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  api:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    restart: on-failure:2
    environment:
      DB_HOST: db
    ports:
      - '8000:8000'
